name: dating_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_staggered_grid_view: "^0.3.2"
  image_picker: ^0.7.2+1
  curved_navigation_bar: ^0.3.3
  tcard: ^1.2.2
  agora_rtc_engine: ^3.2.1
  permission_handler: ^6.0.1+1
  agora_rtm: ^0.9.10



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/1.gif
    - assets/2.gif
    - assets/3.gif
    - assets/female.png
    - assets/heterosexual.svg
    - assets/gay.svg
    - assets/lesbian.svg
    - assets/bisexual.svg
    - assets/interest1.jpg
    - assets/interest2.jpg
    - assets/interest3.jpg
    - assets/interest4.jpg
    - assets/interest5.jpg
    - assets/interest6.jpg
    - assets/interest7.jpg
    - assets/interest8.jpg
    - assets/male.png
    - assets/default_profile_pic.jpg
    - assets/couple.jpg
    - assets/message.svg
    - assets/user.svg
    - assets/magnifying-glass.svg
    - assets/male/1.jpg
    - assets/male/2.jpg
    - assets/male/3.jpg
    - assets/male/4.jpg
    - assets/male/5.jpg
    - assets/male/6.jpg
    - assets/male/7.jpg
    - assets/male/8.jpg
    - assets/male/9.jpg
    - assets/male/10.jpg
    - assets/female/1.jpg
    - assets/female/2.jpg
    - assets/female/3.jpg
    - assets/female/4.jpg
    - assets/female/5.jpg
    - assets/female/6.jpg
    - assets/female/7.jpg
    - assets/female/8.jpg
    - assets/female/9.jpg
    - assets/female/10.jpg
    - assets/female/11.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
